In [3]:
# Data Cleaning & Preprocessing

#This section performs all common preprocessing steps required before completing the analysis tasks. The cleaned dataset is reused throughout Tasks 1–6.

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("../data/Play Store Data.csv")
reviews_df = pd.read_csv("../data/User Reviews.csv")

print(df.shape)
print(reviews_df.shape)

(10841, 13)
(64295, 5)

In [6]:
df["Installs"] = (
    df["Installs"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("+", "", regex=False)
)

df["Installs"] = pd.to_numeric(df["Installs"], errors="coerce")

In [7]:
df["Price"] = (
    df["Price"]
    .astype(str)
    .str.replace("$", "", regex=False)
)

df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

In [8]:
df["Reviews"] = pd.to_numeric(df["Reviews"], errors="coerce")

In [9]:
df["Rating"] = pd.to_numeric(df["Rating"], errors="coerce")

In [10]:
df["Size"] = (
    df["Size"]
    .astype(str)
    .str.replace("M", "", regex=False)
    .str.replace("k", "", regex=False)
)

df["Size"] = pd.to_numeric(df["Size"], errors="coerce")

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10840 non-null  float64
 4   Size            9145 non-null   float64
 5   Installs        10840 non-null  float64
 6   Type            10840 non-null  str
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(5), str(8)
memory usage: 1.1 MB

In [49]:
df = df[df["Category"] != "1.9"]

In [12]:
# 📊 Google Play Store Analytics

## Project Overview This project analyzes the Google Play Store dataset using Python, Pandas, and Plotl

#The objective is to perform data cleaning, feature engineering, exploratory data analysis (EDA), and build interactive visualizations based on business requirements.

### Dataset Used
##- Play Store Data.csv
#- User Reviews.csv

### Tools Used
#- Python
#- Pandas
#- NumPy
#- Plotly
#- Jupyter Notebook

In [13]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from datetime import datetime
import pytz
import warnings

warnings.filterwarnings("ignore")

In [14]:
apps_df = pd.read_csv("../data/Play Store Data.csv")
reviews_df = pd.read_csv("../data/User Reviews.csv")

In [15]:
print("Apps Dataset Shape :", apps_df.shape)
print("Reviews Dataset Shape :", reviews_df.shape)

Apps Dataset Shape : (10841, 13)
Reviews Dataset Shape : (64295, 5)

In [16]:
apps_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [17]:
reviews_df.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [18]:
apps_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [19]:
df = apps_df.copy()

In [20]:
## Data Cleaning

#Before performing any analysis, the dataset is cleaned to ensure consistency and accuracy.

#The following transformations are performed:

#- Convert Rating to numeric
#- Convert Reviews to numeric
#- Clean Installs column
#- Convert Price to numeric
#- Convert Size to MB
#- Convert Last Updated to datetime
#- Extract Android Version

In [21]:
df["Rating"] = pd.to_numeric(df["Rating"], errors="coerce")

In [22]:
df["Rating"].head()

0    4.1
1    3.9
2    4.7
3    4.5
4    4.3
Name: Rating, dtype: float64

In [23]:
df["Reviews"] = pd.to_numeric(df["Reviews"], errors="coerce")

In [24]:
df["Reviews"].dtype

dtype('float64')

In [25]:
df["Installs"] = (
    df["Installs"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("+", "", regex=False)
)

df["Installs"] = pd.to_numeric(
    df["Installs"],
    errors="coerce"
)

In [26]:
df["Installs"].head()

0       10000.0
1      500000.0
2     5000000.0
3    50000000.0
4      100000.0
Name: Installs, dtype: float64

In [27]:
df["Price"] = (
    df["Price"]
    .astype(str)
    .str.replace("$", "", regex=False)
)

df["Price"] = pd.to_numeric(
    df["Price"],
    errors="coerce"
)

In [28]:
df["Size_M"] = (
    df["Size"]
    .astype(str)
    .str.replace("M", "", regex=False)
)

df["Size_M"] = pd.to_numeric(
    df["Size_M"],
    errors="coerce"
)

In [29]:
df["Last Updated"] = pd.to_datetime(
    df["Last Updated"],
    errors="coerce"
)

In [30]:
df["Last Updated"].head()

0   2018-01-07
1   2018-01-15
2   2018-08-01
3   2018-06-08
4   2018-06-20
Name: Last Updated, dtype: datetime64[us]

In [31]:
df["Android_Clean"] = (
    df["Android Ver"]
    .astype(str)
    .str.extract(r"(\d+\.\d+)")
)

df["Android_Clean"] = pd.to_numeric(
    df["Android_Clean"],
    errors="coerce"
)

In [32]:
df["Revenue"] = df["Price"] * df["Installs"]

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10840 non-null  float64
 4   Size            10841 non-null  str
 5   Installs        10840 non-null  float64
 6   Type            10840 non-null  str
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10840 non-null  datetime64[us]
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
 13  Size_M          8829 non-null   float64
 14  Android_Clean   9476 non-null   float64
 15  Revenue         10840 non-null  float64
dtypes: datetime64[us](1), float64(7), str(8)
memory usage: 1.3 MB

In [34]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_M,Android_Clean,Revenue
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,10000.0,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,19.0,4.0,0.0
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14M,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,14.0,4.0,0.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,8.7,4.0,0.0
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25M,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,25.0,4.2,0.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8M,100000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,2.8,4.4,0.0

In [35]:
# Task 1: Grouped Bar Chart

### Objective

#Compare the average rating and total review count for the top 10 app categories based on installs after applying the following business rules:

#- Rating ≥ 4.0
##- Size ≥ 10 MB
#- Last Updated in January

#The visualization is available only between **3 PM and 5 PM IST**.

In [36]:
task1_df = df.copy()

task1_df = task1_df[
    (task1_df["Rating"] >= 4.0)
]

task1_df = task1_df[
    (task1_df["Size_M"] >= 10)
]

task1_df = task1_df[
    task1_df["Last Updated"].dt.month == 1
]

task1_df.shape

(131, 16)

In [37]:
top10_categories = (
    task1_df
    .groupby("Category")["Installs"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top10_categories

Category
FAMILY             182494820.0
SPORTS             120511000.0
GAME               115691000.0
ENTERTAINMENT       51000000.0
PERSONALIZATION     15060000.0
PHOTOGRAPHY         10500000.0
LIFESTYLE            5071000.0
EDUCATION            2000000.0
SHOPPING             2000000.0
TOOLS                1010000.0
Name: Installs, dtype: float64

In [38]:
task1_summary = (
    task1_df[
        task1_df["Category"].isin(top10_categories.index)
    ]
    .groupby("Category")
    .agg(
        Average_Rating=("Rating", "mean"),
        Total_Reviews=("Reviews", "sum")
    )
    .reset_index()
)

task1_summary

          Category  Average_Rating  Total_Reviews
0        EDUCATION        4.400000        57645.0
1    ENTERTAINMENT        4.250000      1238948.0
2           FAMILY        4.395455      4544623.0
3             GAME        4.313333      2397589.0
4        LIFESTYLE        4.380000        42809.0
5  PERSONALIZATION        4.475000       155996.0
6      PHOTOGRAPHY        4.150000       563720.0
7         SHOPPING        4.200000        19950.0
8           SPORTS        4.342857      1982017.0
9            TOOLS        4.200000         8010.0

In [39]:
task1_summary = (
    task1_df[
        task1_df["Category"].isin(top10_categories.index)
    ]
    .groupby("Category")
    .agg(
        Average_Rating=("Rating", "mean"),
        Total_Reviews=("Reviews", "sum")
    )
    .reset_index()
)

task1_summary["Average_Rating"] = (
    task1_summary["Average_Rating"]
    .round(2)
)

task1_summary

          Category  Average_Rating  Total_Reviews
0        EDUCATION            4.40        57645.0
1    ENTERTAINMENT            4.25      1238948.0
2           FAMILY            4.40      4544623.0
3             GAME            4.31      2397589.0
4        LIFESTYLE            4.38        42809.0
5  PERSONALIZATION            4.47       155996.0
6      PHOTOGRAPHY            4.15       563720.0
7         SHOPPING            4.20        19950.0
8           SPORTS            4.34      1982017.0
9            TOOLS            4.20         8010.0

In [40]:
from datetime import datetime
import pytz
import plotly.graph_objects as go

# Current IST Time
ist = pytz.timezone("Asia/Kolkata")
current_time = datetime.now(ist)

if 15 <= current_time.hour < 17:

    # Create Figure
    task1_fig = go.Figure()

    # Average Rating (Bar)
    task1_fig.add_trace(
        go.Bar(
            x=task1_summary["Category"],
            y=task1_summary["Average_Rating"],
            name="Average Rating",
            yaxis="y",
            hovertemplate="<b>%{x}</b><br>Average Rating: %{y:.2f}<extra></extra>"
        )
    )

    # Total Reviews (Line)
    task1_fig.add_trace(
        go.Scatter(
            x=task1_summary["Category"],
            y=task1_summary["Total_Reviews"],
            mode="lines+markers",
            name="Total Reviews",
            yaxis="y2",
            hovertemplate="<b>%{x}</b><br>Total Reviews: %{y:,.0f}<extra></extra>"
        )
    )

    # Layout
    task1_fig.update_layout(
        title="Top 10 Categories by Installs (January Updates Only)",
        template="plotly_white",
        xaxis_title="Category",

        yaxis=dict(
            title="Average Rating"
        ),

        yaxis2=dict(
            title="Total Reviews",
            overlaying="y",
            side="right"
        ),

        hovermode="x unified",
        height=600,

        legend=dict(
            orientation="h",
            y=1.1,
            x=0.3
        )
    )

    # Show Chart
    task1_fig.show()

    # Save Interactive HTML
    task1_fig.write_html("tasks/Task_1/task1_chart.html")

    print("✅ Task 1 chart saved successfully!")

else:
    print("This graph is available only between 3 PM and 5 PM IST.")

This graph is available only between 3 PM and 5 PM IST.

In [41]:
## Task 1 Insights

#After filtering the dataset to include only apps with:
#- Rating ≥ 4.0
#- Size ≥ 10 MB
#- Last Updated in January

#the following observations were made:

#- **FAMILY** category accumulated the highest number of reviews among the selected categories.
#- **PERSONALIZATION** achieved the highest average rating.
#- **TOOLS** has comparatively fewer reviews despite meeting all filtering criteria.
#- The visualization compares user satisfaction (Average Rating) with user engagement (Total Reviews) for the top installed categories.
#- The chart is configured to be displayed only between **3 PM and 5 PM IST**.

In [42]:
## Assumptions

#- Average Rating was calculated after applying all required filters.
#- Total Reviews were aggregated at the category level.
#- Categories were ranked based on total installs after applying the required filters.
#- Apps with missing or invalid values were automatically excluded during data cleaning.

In [43]:
import os

os.makedirs("tasks/Task_1", exist_ok=True)

print("Task_1 folder created successfully!")

Task_1 folder created successfully!

In [44]:
task1_summary.to_csv(
    "tasks/Task_1/task1_summary.csv",
    index=False
)

print("Task 1 summary saved successfully!")

Task 1 summary saved successfully!

In [45]:
task1_fig.write_html("tasks/Task_1/task1_chart.html")

print("✅ Task 1 chart saved successfully!")

NameError: name 'task1_fig' is not defined

In [ ]:
import os

os.path.exists("tasks/Task_1/task1_chart.html")

In [ ]:
# Task 2: Interactive Choropleth Map

## Objective

#Create an interactive Plotly Choropleth map to visualize installs across representative countries for the top 5 app categories after applying the required business filters.

### Business Rules

#- Display only the Top 5 categories based on installs.
#- Exclude categories starting with A, C, G, or S.
#- Include only categories with installs greater than 1,000,000.
#- Display the visualization only between **6 PM and 8 PM IST**.

#> **Note:** The original Google Play Store dataset does not contain geographical information. Representative countries will be assigned only for visualization purposes and this assumption will be documented.

In [ ]:
task2_df = df.copy()

In [ ]:
task2_df = task2_df[
    ~task2_df["Category"].str.startswith(("A", "C", "G", "S"))
]

In [ ]:
task2_df["Category"].unique()

In [ ]:
category_installs = (
    task2_df
    .groupby("Category")["Installs"]
    .sum()
    .reset_index()
)

In [ ]:
category_installs

In [ ]:
category_installs = category_installs[
    category_installs["Installs"] > 1000000
]

In [ ]:
category_installs

In [ ]:
category_installs = (
    category_installs
    .sort_values(
        by="Installs",
        ascending=False
    )
    .head(5)
)

In [ ]:
category_installs

In [ ]:
category_installs

In [ ]:
country_mapping = {
    "PRODUCTIVITY": "United States",
    "TOOLS": "Canada",
    "FAMILY": "India",
    "PHOTOGRAPHY": "Australia",
    "NEWS_AND_MAGAZINES": "Germany"
}

category_installs["Country"] = category_installs["Category"].map(country_mapping)

category_installs

In [ ]:
from datetime import datetime
from zoneinfo import ZoneInfo
import plotly.express as px

current_time = datetime.now(ZoneInfo("Asia/Kolkata"))

if 18 <= current_time.hour < 20:

    task2_fig = px.choropleth(
        category_installs,
        locations="Country",
        locationmode="country names",
        color="Installs",
        hover_name="Category",
        hover_data={
            "Country": True,
            "Installs": ":,.0f"
        },
        color_continuous_scale="Viridis",
        title="Global Installs by Top 5 App Categories"
    )

    task2_fig.update_layout(
        template="plotly_white",
        height=650,
        title_x=0.5,
        margin=dict(l=20, r=20, t=70, b=20)
    )

    task2_fig.show()

else:
    print("This graph is available only between 6 PM and 8 PM IST.")

In [ ]:
## Task 2 Insights

#- Only categories with installs greater than one million were included.
#- Representative countries were assigned to visualize the data geographically.

In [ ]:
## Task 2 Assumptions

#- The Google Play Store dataset does not contain Country or Region information.
#- Representative countries were assigned solely for visualization purposes.
#- The geographic mapping does not represent the actual origin of installs.
#- All installs, categories and filtering logic were derived from the original dataset.
#- The map is displayed only between 6 PM IST and 8 PM IST.

In [ ]:
import os

os.makedirs("tasks/Task_2", exist_ok=True)

category_installs.to_csv(
    "tasks/Task_2/task2_summary.csv",
    index=False
)

print("Task 2 summary saved successfully!")

In [ ]:
task2_fig.write_html(
    r"C:\Users\Prathamesh\Desktop\Google_Playstore_Project\tasks\Task_2\task2_chart.html"
)

print("✅ Task 2 chart saved successfully!")

In [ ]:
import pandas as pd

df = pd.read_csv("../data/Play Store Data.csv")
reviews_df = pd.read_csv("../data/User Reviews.csv")

print(df.shape)
print(reviews_df.shape)

In [ ]:
df["Type"].value_counts(dropna=False)

In [ ]:
df["Android Ver"].unique()[:20]

In [ ]:
df["Price"].head(10)

In [ ]:
df["Price"].dtype

In [ ]:
df["Size"].head(10)

In [ ]:
df["Content Rating"].value_counts()

In [ ]:
# Task 3: Dual-Axis Chart (Average Installs vs Revenue)

### Objective
#Create a dual-axis chart comparing the average installs and estimated revenue for Free vs Paid apps within the top 3 app categories after applying the required business filters.

### Business Rules
#- Installs ≥ 10,000
#- Revenue ≥ $10,000
#- Android Version > 4.0
#- App Size > 15 MB
#- Content Rating = Everyone
#- App Name length ≤ 30 characters
#- Show only the Top 3 app categories
#- Display the graph only between 1 PM IST and 2 PM IST.

In [ ]:
task3_df = df.copy()

In [ ]:
# Installs >= 10,000
task3_df = task3_df[task3_df["Installs"] >= 10000]

# Content Rating = Everyone
task3_df = task3_df[task3_df["Content Rating"] == "Everyone"]

# App Name <= 30 characters
task3_df = task3_df[task3_df["App"].str.len() <= 30]

In [ ]:
task3_df["Android Ver"] = (
    task3_df["Android Ver"]
    .astype(str)
    .str.extract(r'(\d+\.?\d*)')[0]
)

task3_df["Android Ver"] = pd.to_numeric(
    task3_df["Android Ver"],
    errors="coerce"
)

task3_df = task3_df[task3_df["Android Ver"] > 4.0]

In [ ]:
# ============================
# Task 3 - Apply Filters
# ============================

task3_df = df.copy()

# 1. Installs >= 10,000
task3_df = task3_df[
    task3_df["Installs"] >= 10000
]

# 2. Content Rating = Everyone
task3_df = task3_df[
    task3_df["Content Rating"] == "Everyone"
]

# 3. App Name <= 30 characters
task3_df = task3_df[
    task3_df["App"].str.len() <= 30
]

# 4. Android Version > 4.0
task3_df["Android Ver"] = (
    task3_df["Android Ver"]
    .astype(str)
    .str.extract(r'(\d+\.?\d*)')[0]
)

task3_df["Android Ver"] = pd.to_numeric(
    task3_df["Android Ver"],
    errors="coerce"
)

task3_df = task3_df[
    task3_df["Android Ver"] > 4.0
]

# 5. Size > 15 MB
task3_df = task3_df[
    task3_df["Size"] > 15
]

print("Filtered Data Shape:", task3_df.shape)

In [ ]:
task3_df.shape

In [ ]:
task3_df = df.copy()
print("Original:", task3_df.shape)

In [ ]:
task3_df = task3_df[task3_df["Installs"] >= 10000]
print("After Installs:", task3_df.shape)

In [ ]:
task3_df = task3_df[task3_df["Content Rating"] == "Everyone"]
print("After Content Rating:", task3_df.shape)

In [ ]:
task3_df = task3_df[task3_df["App"].str.len() <= 30]
print("After App Length:", task3_df.shape)

In [ ]:
task3_df["Android Ver"].head(10)

In [ ]:
task3_df["Size"].head(10)

In [ ]:
task3_df["Revenue"] = (
    task3_df["Price"] * task3_df["Installs"]
)

task3_df.head()

In [ ]:
task3_df = task3_df[
    task3_df["Revenue"] >= 10000
]

print(task3_df.shape)

In [ ]:
task3_df["Type"].value_counts()

In [ ]:
top3_categories = (
    task3_df.groupby("Category")["Installs"]
    .sum()
    .sort_values(ascending=False)
    .head(3)
)

top3_categories

In [ ]:
task3_df = task3_df[
    task3_df["Category"].isin(top3_categories.index)
]

print(task3_df.shape)

In [ ]:
summary3 = (
    task3_df.groupby(["Category", "Type"])
    .agg(
        Average_Installs=("Installs", "mean"),
        Revenue=("Revenue", "mean")
    )
    .reset_index()
)

summary3

In [ ]:
task3_df["Type"].value_counts()

In [ ]:
task3_df.groupby("Type")["Revenue"].describe()

In [ ]:
task3_before_revenue = task3_df.copy()

task3_before_revenue["Type"].value_counts()

In [ ]:
task3_debug = df.copy()

print("Original")
print(task3_debug["Type"].value_counts(dropna=False))

In [ ]:
# Installs >= 10000
task3_debug = task3_debug[task3_debug["Installs"] >= 10000]

print("After Installs")
print(task3_debug["Type"].value_counts())

In [ ]:
# Everyone
task3_debug = task3_debug[
    task3_debug["Content Rating"] == "Everyone"
]

print("After Content Rating")
print(task3_debug["Type"].value_counts())

In [ ]:
# App name <=30
task3_debug = task3_debug[
    task3_debug["App"].str.len() <= 30
]

print("After App Length")
print(task3_debug["Type"].value_counts())

In [ ]:
# Android Version
task3_debug["Android Ver"] = (
    task3_debug["Android Ver"]
    .astype(str)
    .str.extract(r'(\d+\.?\d*)')[0]
)

task3_debug["Android Ver"] = pd.to_numeric(
    task3_debug["Android Ver"],
    errors="coerce"
)

task3_debug = task3_debug[
    task3_debug["Android Ver"] > 4.0
]

print("After Android")
print(task3_debug["Type"].value_counts())

In [ ]:
# Size
task3_debug = task3_debug[
    task3_debug["Size"] > 15
]

print("After Size")
print(task3_debug["Type"].value_counts())

In [ ]:
### Assumption

#The estimated revenue was calculated as:

#Revenue = Price × Installs

#After applying the business rule requiring Revenue ≥ $10,000, all Free applications were excluded because their price is $0, resulting in zero estimated revenue. Therefore, the final visualization contains only Paid applications that satisfy all specified conditions.

In [ ]:
from datetime import datetime
from zoneinfo import ZoneInfo
import plotly.graph_objects as go

current_time = datetime.now(ZoneInfo("Asia/Kolkata"))

if 13 <= current_time.hour < 14:

    task3_fig = go.Figure()

    # Average Installs (Bar)
    task3_fig.add_trace(
        go.Bar(
            x=summary3["Category"],
            y=summary3["Average_Installs"],
            name="Average Installs",
            yaxis="y",
            marker_color="steelblue"
        )
    )

    # Revenue (Line)
    task3_fig.add_trace(
        go.Scatter(
            x=summary3["Category"],
            y=summary3["Revenue"],
            mode="lines+markers",
            name="Revenue",
            yaxis="y2",
            line=dict(color="red", width=3)
        )
    )

    task3_fig.update_layout(
        title="Average Installs vs Revenue (Top 3 Categories)",
        template="plotly_white",
        xaxis_title="Category",

        yaxis=dict(
            title="Average Installs"
        ),

        yaxis2=dict(
            title="Revenue ($)",
            overlaying="y",
            side="right"
        ),

        hovermode="x unified",
        height=600,

        legend=dict(
            orientation="h",
            y=1.1,
            x=0.3
        )
    )

    task3_fig.show()

else:
    print("This graph is available only between 1 PM and 2 PM IST.")

In [ ]:
task3_fig.write_html(
    r"C:\Users\Prathamesh\Desktop\Google_Playstore_Project\tasks\Task_3\task3_chart.html"
)

In [ ]:
summary3.to_csv(
    r"C:\Users\Prathamesh\Desktop\Google_Playstore_Project\tasks\Task_3\task3_summary.csv",
    index=False
)

In [ ]:
## Task 3 Insights

#- Paid applications generated significantly higher estimated revenue after applying the business rules.
#- The top 3 categories were selected based on total installs after filtering.
#- Apps with fewer than 10,000 installs, Android version 4.0 or lower, size less than 15 MB, and non-"Everyone" content ratings were excluded.
#- The dual-axis chart compares average installs and estimated revenue for the qualifying categories.

In [ ]:
## Task 3 Assumptions

#- Revenue was estimated as Price × Installs because the original dataset does not contain revenue information.
#- After applying the Revenue ≥ $10,000 filter, all Free applications were excluded because their price is $0, resulting in zero estimated revenue.
#- Therefore, the final visualization contains only qualifying Paid applications.
#- The visualization is displayed only between 1 PM IST and 2 PM IST.

In [ ]:
task3_fig.write_html(
    r"C:\Users\Prathamesh\Desktop\Google_Playstore_Project\tasks\Task_3\task3_chart.html"
)

print("✅ Task 3 HTML saved successfully!")

In [ ]:
summary3.to_csv(
    r"C:\Users\Prathamesh\Desktop\Google_Playstore_Project\tasks\Task_3\task3_summary.csv",
    index=False
)

print("✅ Task 3 Summary saved successfully!")

In [ ]:
# Task 4: Time Series Analysis of Total Installs

### Objective
#Plot a time series line chart showing the trend of total installs over time segmented by app category after applying all specified business rules.

### Business Rules
#- App name should not start with X, Y, or Z.
#- App category should start with E, C, or B.
#- Reviews > 500.
#- App name should not contain the letter "S".
#- Translate:
 # - Beauty → Hindi
 #- Business → Tamil
 # - Dating → German
#- Highlight periods where month-over-month install growth exceeds 20%.
#- Display the graph only between 6 PM IST and 9 PM IST.

In [48]:
task4_df = df.copy()

task4_df = task4_df[
    task4_df["Reviews"] > 500
]

task4_df = task4_df[
    ~task4_df["App"].str.startswith(("X", "Y", "Z"), na=False)
]

task4_df = task4_df[
    ~task4_df["App"].str.contains("S", case=False, na=False)
]

task4_df = task4_df[
    task4_df["Category"].str.startswith(("B", "C", "E"))
]

print(task4_df.shape)
print(task4_df["Category"].value_counts())

(245, 16)
Category
COMMUNICATION          77
ENTERTAINMENT          56
BOOKS_AND_REFERENCE    40
EDUCATION              31
BUSINESS               26
COMICS                  7
BEAUTY                  4
EVENTS                  4
Name: count, dtype: int64

In [50]:
task4_df["Month"] = task4_df["Last Updated"].dt.to_period("M").astype(str)

In [51]:
translation = {
    "BEAUTY": "सौंदर्य",
    "BUSINESS": "வணிகம்",
    "DATING": "Dating"
}

task4_df["Category"] = task4_df["Category"].replace(translation)

In [52]:
monthly_installs = (
    task4_df.groupby(["Month", "Category"])["Installs"]
    .sum()
    .reset_index()
)

monthly_installs.head()

     Month       Category    Installs
0  2014-01  COMMUNICATION    100000.0
1  2014-03  COMMUNICATION    100000.0
2  2014-05         வணிகம்    100000.0
3  2014-07  COMMUNICATION  10000000.0
4  2014-07      EDUCATION     10000.0

In [54]:
monthly_installs = monthly_installs.sort_values(
    ["Category", "Month"]
)

monthly_installs["Growth"] = (
    monthly_installs.groupby("Category")["Installs"]
    .pct_change()
)

monthly_installs.head(15)

      Month             Category     Installs     Growth
5   2014-10  BOOKS_AND_REFERENCE     500000.0        NaN
6   2014-11  BOOKS_AND_REFERENCE    5000000.0   9.000000
10  2015-07  BOOKS_AND_REFERENCE   10000000.0   1.000000
18  2016-06  BOOKS_AND_REFERENCE      60000.0  -0.994000
21  2016-08  BOOKS_AND_REFERENCE     100000.0   0.666667
27  2017-02  BOOKS_AND_REFERENCE     100000.0   0.000000
29  2017-04  BOOKS_AND_REFERENCE    1000000.0   9.000000
31  2017-05  BOOKS_AND_REFERENCE     100000.0  -0.900000
32  2017-07  BOOKS_AND_REFERENCE     100000.0   0.000000
33  2017-08  BOOKS_AND_REFERENCE   10010000.0  99.100000
38  2017-11  BOOKS_AND_REFERENCE    2000000.0  -0.800200
49  2018-04  BOOKS_AND_REFERENCE    1050000.0  -0.475000
51  2018-05  BOOKS_AND_REFERENCE   40600000.0  37.666667
58  2018-06  BOOKS_AND_REFERENCE   52100000.0   0.283251
64  2018-07  BOOKS_AND_REFERENCE  201600000.0   2.869482

In [55]:
monthly_installs["Highlight"] = (
    monthly_installs["Growth"] > 0.20
)

monthly_installs.head(15)

      Month             Category     Installs     Growth  Highlight
5   2014-10  BOOKS_AND_REFERENCE     500000.0        NaN      False
6   2014-11  BOOKS_AND_REFERENCE    5000000.0   9.000000       True
10  2015-07  BOOKS_AND_REFERENCE   10000000.0   1.000000       True
18  2016-06  BOOKS_AND_REFERENCE      60000.0  -0.994000      False
21  2016-08  BOOKS_AND_REFERENCE     100000.0   0.666667       True
27  2017-02  BOOKS_AND_REFERENCE     100000.0   0.000000      False
29  2017-04  BOOKS_AND_REFERENCE    1000000.0   9.000000       True
31  2017-05  BOOKS_AND_REFERENCE     100000.0  -0.900000      False
32  2017-07  BOOKS_AND_REFERENCE     100000.0   0.000000      False
33  2017-08  BOOKS_AND_REFERENCE   10010000.0  99.100000       True
38  2017-11  BOOKS_AND_REFERENCE    2000000.0  -0.800200      False
49  2018-04  BOOKS_AND_REFERENCE    1050000.0  -0.475000      False
51  2018-05  BOOKS_AND_REFERENCE   40600000.0  37.666667       True
58  2018-06  BOOKS_AND_REFERENCE   52100000.0   0.283251       True
64  2018-07  BOOKS_AND_REFERENCE  201600000.0   2.869482       True

In [85]:
from datetime import datetime
from zoneinfo import ZoneInfo
import plotly.graph_objects as go
import pandas as pd

current_time = datetime.now(ZoneInfo("Asia/Kolkata"))

if 18 <= current_time.hour < 21:

    task4_fig = go.Figure()

    colors = {
        "COMMUNICATION": "#2563EB",
        "EDUCATION": "#16A34A",
        "ENTERTAINMENT": "#9333EA",
        "BOOKS_AND_REFERENCE": "#EA580C",
        "COMICS": "#92400E",
        "EVENTS": "#0891B2",
        "सौंदर्य": "#DB2777",
        "வணிகம்": "#DC2626"
    }

    # ============================================================
    # Highlight months with >20% MoM growth
    # ============================================================

    highlight_months = monthly_installs.loc[
        monthly_installs["Highlight"],
        "Month"
    ].unique()

    for month in highlight_months:

        task4_fig.add_vrect(

            x0=pd.Period(month).start_time,
            x1=pd.Period(month).end_time,

            fillcolor="rgba(255,99,71,0.16)",

            line_width=0,

            layer="below"
        )

    # ============================================================
    # Plot one line per category
    # ============================================================

    for category in monthly_installs["Category"].unique():

        category_df = (
            monthly_installs[
                monthly_installs["Category"] == category
            ]
            .sort_values("Month")
        )

        color = colors.get(category, "#3B82F6")

        task4_fig.add_trace(

            go.Scatter(

                x=pd.to_datetime(category_df["Month"]),

                y=category_df["Installs"],

                mode="lines+markers",

                name=category,

                line=dict(
                    color=color,
                    width=4,
                    shape="spline",
                    smoothing=0.5
                ),

                marker=dict(
                    size=9,
                    symbol="circle",
                    color=color,
                    line=dict(
                        color="white",
                        width=1.5
                    )
                ),

                customdata=category_df["Growth"],

                hovertemplate=
                "<b>%{fullData.name}</b><br>"
                "Month: %{x|%b %Y}<br>"
                "Total Installs: %{y:,.0f}<br>"
                "Growth: %{customdata:.2%}"
                "<extra></extra>"
            )
        )

    # ============================================================
    # Layout
    # ============================================================

    task4_fig.update_layout(

        title=dict(
            text="<b>Monthly Install Trend by App Category</b><br>"
                 "<sup>Periods with >20% Month-over-Month Install Growth are Highlighted</sup>",
            x=0.5,
            y=0.97,
            xanchor="center",
            font=dict(
                family="Arial",
                size=24
            )
        ),

        template="plotly_white",

        height=760,

        hovermode="x unified",

        font=dict(
            family="Arial",
            size=13,
            color="#2C3E50"
        ),

        plot_bgcolor="white",

        paper_bgcolor="white",

        legend=dict(
            orientation="h",
            y=1.08,
            x=0.5,
            xanchor="center",
            bgcolor="rgba(255,255,255,0)",
            borderwidth=0,
            font=dict(size=12)
        ),

        margin=dict(
            l=70,
            r=40,
            t=120,
            b=70
        ),

        xaxis=dict(
            title="<b>Last Updated Month</b>",
            tickformat="%b\n%Y",
            tickangle=0,
            showgrid=False,
            showline=True,
            linewidth=1,
            linecolor="lightgray"
        ),

        yaxis=dict(
            title="<b>Total Installs</b>",
            gridcolor="rgba(180,180,180,0.30)",
            zeroline=False,
            showline=True,
            linewidth=1,
            linecolor="lightgray",
            separatethousands=True
        )
    )

    task4_fig.show()

else:

    print("This graph is available only between 6 PM IST and 9 PM IST.")

This graph is available only between 6 PM IST and 9 PM IST.

In [69]:
task4_fig.write_html(
    r"C:\Users\Prathamesh\Desktop\Google_Playstore_Project\tasks\Task_4\task4_chart.html"
)

print("✅ Task 4 HTML saved successfully!")

✅ Task 4 HTML saved successfully!

In [70]:
monthly_installs.to_csv(
    r"C:\Users\Prathamesh\Desktop\Google_Playstore_Project\tasks\Task_4\task4_summary.csv",
    index=False
)

print("✅ Task 4 Summary saved successfully!")

✅ Task 4 Summary saved successfully!

In [71]:
## Task 4 Insights

#- Communication recorded the highest total installs across the selected categories.
#- Significant month-over-month growth (>20%) was observed in multiple categories and is highlighted on the chart.
#- Business rules filtered the dataset to include only apps with more than 500 reviews, app names not starting with X, Y, or Z, app names without the letter "S", and categories beginning with B, C, or E.
#- Category names were translated as required: Beauty (Hindi) and Business (Tamil).

In [72]:
## Task 4 Assumptions

#- Month-over-month growth was calculated using the Last Updated month.
#- Growth greater than 20% was considered significant and highlighted on the visualization.
#- The Dating category translation was not displayed because it did not satisfy the category filter (categories starting with B, C, or E).
#- The visualization is displayed only between 6 PM IST and 9 PM IST.

In [73]:
# Task 5: Bubble Chart - App Size vs Average Rating

### Objective
#Create an interactive bubble chart to analyze the relationship between app size (MB) and average rating.

### Business Rules
#- Rating > 3.5
#- Installs > 50,000
#- Reviews > 500
#- Categories:
  #- GAME
  #- BEAUTY
  #- BUSINESS
  #- COMICS
  #- COMMUNICATION
  #- DATING
  #- ENTERTAINMENT
  #- EVENTS
  #- SOCIAL
#- App name should not contain the letter "S".
#- Sentiment Subjectivity > 0.5
#- Bubble size represents number of installs.
#- Highlight GAME category using Pink color.
#- Translate:
  #- Beauty → Hindi
  #- Business → Tamil
  #- Dating → German
#- Display only between 5 PM IST and 7 PM IST.

In [76]:
# Average sentiment subjectivity for each app
subjectivity_df = (
    reviews_df.groupby("App", as_index=False)["Sentiment_Subjectivity"]
    .mean()
)

# Merge with Play Store dataset
task5_df = df.merge(
    subjectivity_df,
    on="App",
    how="left"
)

print(task5_df.shape)

task5_df.head()

(10840, 17)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_M,Android_Clean,Revenue,Sentiment_Subjectivity
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,10000.0,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,19.0,4.0,0.0,NaN
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14M,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,14.0,4.0,0.0,0.64154
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,8.7,4.0,0.0,NaN
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25M,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,25.0,4.2,0.0,NaN
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8M,100000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,2.8,4.4,0.0,NaN

In [78]:
task5_df = task5_df.dropna(
    subset=["Sentiment_Subjectivity"]
)

print(task5_df.shape)

(1229, 17)

In [79]:
categories = [
    "GAME",
    "BEAUTY",
    "BUSINESS",
    "COMICS",
    "COMMUNICATION",
    "DATING",
    "ENTERTAINMENT",
    "EVENTS",
    "SOCIAL"
]

task5_df = task5_df[
    (task5_df["Rating"] > 3.5) &
    (task5_df["Installs"] > 50000) &
    (task5_df["Reviews"] > 500) &
    (task5_df["Sentiment_Subjectivity"] > 0.5) &
    (task5_df["Category"].isin(categories)) &
    (~task5_df["App"].str.contains("S", case=False, na=False))
]

print(task5_df.shape)
print(task5_df["Category"].value_counts())

(50, 17)
Category
GAME             27
COMMUNICATION     9
DATING            9
BUSINESS          2
ENTERTAINMENT     2
SOCIAL            1
Name: count, dtype: int64

In [81]:
translations = {
    "BEAUTY": "सौंदर्य",
    "BUSINESS": "வணிகம்",
    "DATING": "Dating"
}

task5_df["Category"] = (
    task5_df["Category"]
    .replace(translations)
)

In [82]:
color_map = {
    "GAME": "#FF69B4",          # Pink (required)
    "COMMUNICATION": "#2563EB",
    "Dating": "#10B981",        # German translation
    "வணிகம்": "#DC2626",         # Tamil
    "ENTERTAINMENT": "#8B5CF6",
    "SOCIAL": "#F59E0B",
    "सौंदर्य": "#EC4899"         # Hindi
}

In [95]:
from datetime import datetime
from zoneinfo import ZoneInfo
import plotly.express as px

current_time = datetime.now(ZoneInfo("Asia/Kolkata"))

if 17 <= current_time.hour < 19:

    color_map = {
        "GAME": "#FF69B4",          # Pink (Required)
        "COMMUNICATION": "#2563EB",
        "Dating": "#10B981",        # German Translation
        "வணிகம்": "#DC2626",         # Tamil Translation
        "ENTERTAINMENT": "#8B5CF6",
        "SOCIAL": "#F59E0B",
        "सौंदर्य": "#EC4899"         # Hindi Translation
    }

    task5_fig = px.scatter(

        task5_df,

        x="Size_M",
        y="Rating",

        size="Installs",

        color="Category",

        color_discrete_map=color_map,

        hover_name="App",

        hover_data={
            "Category": True,
            "Size_M": ":.1f",
            "Rating": ":.1f",
            "Reviews": ":,.0f",
            "Installs": ":,.0f",
            "Sentiment_Subjectivity": ":.2f"
        },

        size_max=45,

        title="App Size vs Average Rating"
    )

    task5_fig.update_traces(

        marker=dict(

            opacity=0.78,

            line=dict(
                width=1.2,
                color="white"
            )

        )
    )

    task5_fig.update_layout(

        title=dict(

            text="<b>App Size vs Average Rating</b><br>"
                 "<sup>Bubble Size Represents Total Installs | Filtered by Business Rules</sup>",

            x=0.5,

            y=0.97,

            xanchor="center",

            font=dict(
                family="Arial",
                size=24
            )

        ),

        template="plotly_white",

        height=720,

        hovermode="closest",

        font=dict(
            family="Arial",
            size=13,
            color="#2C3E50"
        ),

        plot_bgcolor="white",

        paper_bgcolor="white",

        legend=dict(

            orientation="h",

            y=1.08,

            x=0.5,

            xanchor="center",

            bgcolor="rgba(255,255,255,0)",

            borderwidth=0,

            font=dict(size=12)

        ),

        margin=dict(

            l=70,

            r=40,

            t=120,

            b=70

        ),

        xaxis=dict(

            title="<b>App Size (MB)</b>",

            showgrid=True,

            gridcolor="rgba(220,220,220,0.35)",

            zeroline=False

        ),

        yaxis=dict(

            title="<b>Average Rating</b>",

            range=[3.5, 5.1],

            showgrid=True,

            gridcolor="rgba(220,220,220,0.35)",

            zeroline=False

        )

    )

    task5_fig.show()

else:

    print("This graph is available only between 5 PM IST and 7 PM IST.")

This graph is available only between 5 PM IST and 7 PM IST.

In [91]:
task5_fig.write_html(
    r"C:\Users\Prathamesh\Desktop\Google_Playstore_Project\tasks\Task_5\task5_chart.html"
)

print("✅ Task 5 HTML saved successfully!")

✅ Task 5 HTML saved successfully!

In [92]:
task5_df.to_csv(
    r"C:\Users\Prathamesh\Desktop\Google_Playstore_Project\tasks\Task_5\task5_summary.csv",
    index=False
)

print("✅ Task 5 Summary saved successfully!")

✅ Task 5 Summary saved successfully!

In [93]:
## Task 5 Insights

#- The Game category contains the highest number of qualifying apps after applying all business rules and is highlighted in pink.
#- Larger app sizes do not necessarily correspond to higher ratings, indicating a weak relationship between app size and user ratings.
#- Apps with higher install counts appear as larger bubbles, making it easy to identify the most popular applications.
#- Communication, Dating, Business, Entertainment, and Social categories remain after filtering, while Beauty, Comics, and Events have no qualifying apps.

In [94]:
## Task 5 Assumptions

#- Bubble size represents the total number of installs for each app.
#- Sentiment Subjectivity was calculated as the average value per app from the User Reviews dataset before merging.
#- Beauty, Comics, and Events categories are not displayed because no apps satisfied all filtering conditions.
#- Category translations were applied as required:
  #- Beauty → Hindi (सौंदर्य)
  #- Business → Tamil (வணிகம்)
  #- Dating → German (Dating)
#- The visualization is available only between 5 PM IST and 7 PM IST.