In [3]:
# 📊 Google Play Store Analytics

## Project Overview This project analyzes the Google Play Store dataset using Python, Pandas, and Plotl

#The objective is to perform data cleaning, feature engineering, exploratory data analysis (EDA), and build interactive visualizations based on business requirements.

### Dataset Used
##- Play Store Data.csv
#- User Reviews.csv

### Tools Used
#- Python
#- Pandas
#- NumPy
#- Plotly
#- Jupyter Notebook

In [4]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from datetime import datetime
import pytz
import warnings

warnings.filterwarnings("ignore")

In [5]:
apps_df = pd.read_csv("../data/Play Store Data.csv")
reviews_df = pd.read_csv("../data/User Reviews.csv")

In [6]:
print("Apps Dataset Shape :", apps_df.shape)
print("Reviews Dataset Shape :", reviews_df.shape)

Apps Dataset Shape : (10841, 13)
Reviews Dataset Shape : (64295, 5)

In [7]:
apps_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [8]:
reviews_df.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [9]:
apps_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [10]:
df = apps_df.copy()

In [11]:
## Data Cleaning

#Before performing any analysis, the dataset is cleaned to ensure consistency and accuracy.

#The following transformations are performed:

#- Convert Rating to numeric
#- Convert Reviews to numeric
#- Clean Installs column
#- Convert Price to numeric
#- Convert Size to MB
#- Convert Last Updated to datetime
#- Extract Android Version

In [12]:
df["Rating"] = pd.to_numeric(df["Rating"], errors="coerce")

In [13]:
df["Rating"].head()

0    4.1
1    3.9
2    4.7
3    4.5
4    4.3
Name: Rating, dtype: float64

In [14]:
df["Reviews"] = pd.to_numeric(df["Reviews"], errors="coerce")

In [15]:
df["Reviews"].dtype

dtype('float64')

In [16]:
df["Installs"] = (
    df["Installs"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("+", "", regex=False)
)

df["Installs"] = pd.to_numeric(
    df["Installs"],
    errors="coerce"
)

In [17]:
df["Installs"].head()

0       10000.0
1      500000.0
2     5000000.0
3    50000000.0
4      100000.0
Name: Installs, dtype: float64

In [18]:
df["Price"] = (
    df["Price"]
    .astype(str)
    .str.replace("$", "", regex=False)
)

df["Price"] = pd.to_numeric(
    df["Price"],
    errors="coerce"
)

In [19]:
df["Size_M"] = (
    df["Size"]
    .astype(str)
    .str.replace("M", "", regex=False)
)

df["Size_M"] = pd.to_numeric(
    df["Size_M"],
    errors="coerce"
)

In [20]:
df["Last Updated"] = pd.to_datetime(
    df["Last Updated"],
    errors="coerce"
)

In [21]:
df["Last Updated"].head()

0   2018-01-07
1   2018-01-15
2   2018-08-01
3   2018-06-08
4   2018-06-20
Name: Last Updated, dtype: datetime64[us]

In [22]:
df["Android_Clean"] = (
    df["Android Ver"]
    .astype(str)
    .str.extract(r"(\d+\.\d+)")
)

df["Android_Clean"] = pd.to_numeric(
    df["Android_Clean"],
    errors="coerce"
)

In [23]:
df["Revenue"] = df["Price"] * df["Installs"]

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10840 non-null  float64
 4   Size            10841 non-null  str
 5   Installs        10840 non-null  float64
 6   Type            10840 non-null  str
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10840 non-null  datetime64[us]
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
 13  Size_M          8829 non-null   float64
 14  Android_Clean   9476 non-null   float64
 15  Revenue         10840 non-null  float64
dtypes: datetime64[us](1), float64(7), str(8)
memory usage: 1.3 MB

In [25]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_M,Android_Clean,Revenue
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,10000.0,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,19.0,4.0,0.0
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14M,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,14.0,4.0,0.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,8.7,4.0,0.0
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25M,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,25.0,4.2,0.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8M,100000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,2.8,4.4,0.0

In [26]:
# Task 1: Grouped Bar Chart

### Objective

#Compare the average rating and total review count for the top 10 app categories based on installs after applying the following business rules:

#- Rating ≥ 4.0
##- Size ≥ 10 MB
#- Last Updated in January

#The visualization is available only between **3 PM and 5 PM IST**.

In [27]:
task1_df = df.copy()

task1_df = task1_df[
    (task1_df["Rating"] >= 4.0)
]

task1_df = task1_df[
    (task1_df["Size_M"] >= 10)
]

task1_df = task1_df[
    task1_df["Last Updated"].dt.month == 1
]

task1_df.shape

(131, 16)

In [28]:
top10_categories = (
    task1_df
    .groupby("Category")["Installs"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top10_categories

Category
FAMILY             182494820.0
SPORTS             120511000.0
GAME               115691000.0
ENTERTAINMENT       51000000.0
PERSONALIZATION     15060000.0
PHOTOGRAPHY         10500000.0
LIFESTYLE            5071000.0
EDUCATION            2000000.0
SHOPPING             2000000.0
TOOLS                1010000.0
Name: Installs, dtype: float64

In [29]:
task1_summary = (
    task1_df[
        task1_df["Category"].isin(top10_categories.index)
    ]
    .groupby("Category")
    .agg(
        Average_Rating=("Rating", "mean"),
        Total_Reviews=("Reviews", "sum")
    )
    .reset_index()
)

task1_summary

          Category  Average_Rating  Total_Reviews
0        EDUCATION        4.400000        57645.0
1    ENTERTAINMENT        4.250000      1238948.0
2           FAMILY        4.395455      4544623.0
3             GAME        4.313333      2397589.0
4        LIFESTYLE        4.380000        42809.0
5  PERSONALIZATION        4.475000       155996.0
6      PHOTOGRAPHY        4.150000       563720.0
7         SHOPPING        4.200000        19950.0
8           SPORTS        4.342857      1982017.0
9            TOOLS        4.200000         8010.0

In [30]:
task1_summary = (
    task1_df[
        task1_df["Category"].isin(top10_categories.index)
    ]
    .groupby("Category")
    .agg(
        Average_Rating=("Rating", "mean"),
        Total_Reviews=("Reviews", "sum")
    )
    .reset_index()
)

task1_summary["Average_Rating"] = (
    task1_summary["Average_Rating"]
    .round(2)
)

task1_summary

          Category  Average_Rating  Total_Reviews
0        EDUCATION            4.40        57645.0
1    ENTERTAINMENT            4.25      1238948.0
2           FAMILY            4.40      4544623.0
3             GAME            4.31      2397589.0
4        LIFESTYLE            4.38        42809.0
5  PERSONALIZATION            4.47       155996.0
6      PHOTOGRAPHY            4.15       563720.0
7         SHOPPING            4.20        19950.0
8           SPORTS            4.34      1982017.0
9            TOOLS            4.20         8010.0

In [62]:
from datetime import datetime
import pytz
import plotly.graph_objects as go

# Current IST Time
ist = pytz.timezone("Asia/Kolkata")
current_time = datetime.now(ist)

if 15 <= current_time.hour < 17:

    # Create Figure
    task1_fig = go.Figure()

    # Average Rating (Bar)
    task1_fig.add_trace(
        go.Bar(
            x=task1_summary["Category"],
            y=task1_summary["Average_Rating"],
            name="Average Rating",
            yaxis="y",
            hovertemplate="<b>%{x}</b><br>Average Rating: %{y:.2f}<extra></extra>"
        )
    )

    # Total Reviews (Line)
    task1_fig.add_trace(
        go.Scatter(
            x=task1_summary["Category"],
            y=task1_summary["Total_Reviews"],
            mode="lines+markers",
            name="Total Reviews",
            yaxis="y2",
            hovertemplate="<b>%{x}</b><br>Total Reviews: %{y:,.0f}<extra></extra>"
        )
    )

    # Layout
    task1_fig.update_layout(
        title="Top 10 Categories by Installs (January Updates Only)",
        template="plotly_white",
        xaxis_title="Category",

        yaxis=dict(
            title="Average Rating"
        ),

        yaxis2=dict(
            title="Total Reviews",
            overlaying="y",
            side="right"
        ),

        hovermode="x unified",
        height=600,

        legend=dict(
            orientation="h",
            y=1.1,
            x=0.3
        )
    )

    # Show Chart
    task1_fig.show()

    # Save Interactive HTML
    task1_fig.write_html("tasks/Task_1/task1_chart.html")

    print("✅ Task 1 chart saved successfully!")

else:
    print("This graph is available only between 3 PM and 5 PM IST.")

This graph is available only between 3 PM and 5 PM IST.

In [32]:
## Task 1 Insights

#After filtering the dataset to include only apps with:
#- Rating ≥ 4.0
#- Size ≥ 10 MB
#- Last Updated in January

#the following observations were made:

#- **FAMILY** category accumulated the highest number of reviews among the selected categories.
#- **PERSONALIZATION** achieved the highest average rating.
#- **TOOLS** has comparatively fewer reviews despite meeting all filtering criteria.
#- The visualization compares user satisfaction (Average Rating) with user engagement (Total Reviews) for the top installed categories.
#- The chart is configured to be displayed only between **3 PM and 5 PM IST**.

In [33]:
## Assumptions

#- Average Rating was calculated after applying all required filters.
#- Total Reviews were aggregated at the category level.
#- Categories were ranked based on total installs after applying the required filters.
#- Apps with missing or invalid values were automatically excluded during data cleaning.

In [57]:
import os

os.makedirs("tasks/Task_1", exist_ok=True)

print("Task_1 folder created successfully!")

Task_1 folder created successfully!

In [58]:
task1_summary.to_csv(
    "tasks/Task_1/task1_summary.csv",
    index=False
)

print("Task 1 summary saved successfully!")

Task 1 summary saved successfully!

In [63]:
task1_fig.write_html("tasks/Task_1/task1_chart.html")

print("✅ Task 1 chart saved successfully!")

✅ Task 1 chart saved successfully!

In [64]:
import os

os.path.exists("tasks/Task_1/task1_chart.html")

True

In [34]:
# Task 2: Interactive Choropleth Map

## Objective

#Create an interactive Plotly Choropleth map to visualize installs across representative countries for the top 5 app categories after applying the required business filters.

### Business Rules

#- Display only the Top 5 categories based on installs.
#- Exclude categories starting with A, C, G, or S.
#- Include only categories with installs greater than 1,000,000.
#- Display the visualization only between **6 PM and 8 PM IST**.

#> **Note:** The original Google Play Store dataset does not contain geographical information. Representative countries will be assigned only for visualization purposes and this assumption will be documented.

In [36]:
task2_df = df.copy()

In [37]:
task2_df = task2_df[
    ~task2_df["Category"].str.startswith(("A", "C", "G", "S"))
]

In [38]:
task2_df["Category"].unique()

<StringArray>
[             'BEAUTY', 'BOOKS_AND_REFERENCE',            'BUSINESS',
              'DATING',           'EDUCATION',       'ENTERTAINMENT',
              'EVENTS',             'FINANCE',      'FOOD_AND_DRINK',
  'HEALTH_AND_FITNESS',      'HOUSE_AND_HOME',  'LIBRARIES_AND_DEMO',
           'LIFESTYLE',              'FAMILY',             'MEDICAL',
         'PHOTOGRAPHY',    'TRAVEL_AND_LOCAL',               'TOOLS',
     'PERSONALIZATION',        'PRODUCTIVITY',           'PARENTING',
             'WEATHER',       'VIDEO_PLAYERS',  'NEWS_AND_MAGAZINES',
 'MAPS_AND_NAVIGATION',                 '1.9']
Length: 26, dtype: str

In [39]:
category_installs = (
    task2_df
    .groupby("Category")["Installs"]
    .sum()
    .reset_index()
)

In [40]:
category_installs

               Category      Installs
0                   1.9  0.000000e+00
1                BEAUTY  2.719705e+07
2   BOOKS_AND_REFERENCE  1.921470e+09
3              BUSINESS  1.001915e+09
4                DATING  2.643108e+08
5             EDUCATION  8.714520e+08
6         ENTERTAINMENT  2.869160e+09
7                EVENTS  1.597316e+07
8                FAMILY  1.025826e+10
9               FINANCE  8.766487e+08
10       FOOD_AND_DRINK  2.738988e+08
11   HEALTH_AND_FITNESS  1.583073e+09
12       HOUSE_AND_HOME  1.687125e+08
13   LIBRARIES_AND_DEMO  6.299591e+07
14            LIFESTYLE  5.376435e+08
15  MAPS_AND_NAVIGATION  7.242819e+08
16              MEDICAL  5.325744e+07
17   NEWS_AND_MAGAZINES  7.496318e+09
18            PARENTING  3.152111e+07
19      PERSONALIZATION  2.325495e+09
20          PHOTOGRAPHY  1.008825e+10
21         PRODUCTIVITY  1.417609e+10
22                TOOLS  1.145277e+10
23     TRAVEL_AND_LOCAL  6.868887e+09
24        VIDEO_PLAYERS  6.222003e+09
25              WEATHER  4.261005e+08

In [41]:
category_installs = category_installs[
    category_installs["Installs"] > 1000000
]

In [42]:
category_installs

               Category      Installs
1                BEAUTY  2.719705e+07
2   BOOKS_AND_REFERENCE  1.921470e+09
3              BUSINESS  1.001915e+09
4                DATING  2.643108e+08
5             EDUCATION  8.714520e+08
6         ENTERTAINMENT  2.869160e+09
7                EVENTS  1.597316e+07
8                FAMILY  1.025826e+10
9               FINANCE  8.766487e+08
10       FOOD_AND_DRINK  2.738988e+08
11   HEALTH_AND_FITNESS  1.583073e+09
12       HOUSE_AND_HOME  1.687125e+08
13   LIBRARIES_AND_DEMO  6.299591e+07
14            LIFESTYLE  5.376435e+08
15  MAPS_AND_NAVIGATION  7.242819e+08
16              MEDICAL  5.325744e+07
17   NEWS_AND_MAGAZINES  7.496318e+09
18            PARENTING  3.152111e+07
19      PERSONALIZATION  2.325495e+09
20          PHOTOGRAPHY  1.008825e+10
21         PRODUCTIVITY  1.417609e+10
22                TOOLS  1.145277e+10
23     TRAVEL_AND_LOCAL  6.868887e+09
24        VIDEO_PLAYERS  6.222003e+09
25              WEATHER  4.261005e+08

In [43]:
category_installs = (
    category_installs
    .sort_values(
        by="Installs",
        ascending=False
    )
    .head(5)
)

In [44]:
category_installs

              Category      Installs
21        PRODUCTIVITY  1.417609e+10
22               TOOLS  1.145277e+10
8               FAMILY  1.025826e+10
20         PHOTOGRAPHY  1.008825e+10
17  NEWS_AND_MAGAZINES  7.496318e+09

In [45]:
category_installs

              Category      Installs
21        PRODUCTIVITY  1.417609e+10
22               TOOLS  1.145277e+10
8               FAMILY  1.025826e+10
20         PHOTOGRAPHY  1.008825e+10
17  NEWS_AND_MAGAZINES  7.496318e+09

In [46]:
country_mapping = {
    "PRODUCTIVITY": "United States",
    "TOOLS": "Canada",
    "FAMILY": "India",
    "PHOTOGRAPHY": "Australia",
    "NEWS_AND_MAGAZINES": "Germany"
}

category_installs["Country"] = category_installs["Category"].map(country_mapping)

category_installs

              Category      Installs        Country
21        PRODUCTIVITY  1.417609e+10  United States
22               TOOLS  1.145277e+10         Canada
8               FAMILY  1.025826e+10          India
20         PHOTOGRAPHY  1.008825e+10      Australia
17  NEWS_AND_MAGAZINES  7.496318e+09        Germany

In [71]:
from datetime import datetime
from zoneinfo import ZoneInfo
import plotly.express as px

current_time = datetime.now(ZoneInfo("Asia/Kolkata"))

if 18 <= current_time.hour < 20:

    task2_fig = px.choropleth(
        category_installs,
        locations="Country",
        locationmode="country names",
        color="Installs",
        hover_name="Category",
        hover_data={
            "Country": True,
            "Installs": ":,.0f"
        },
        color_continuous_scale="Viridis",
        title="Global Installs by Top 5 App Categories"
    )

    task2_fig.update_layout(
        template="plotly_white",
        height=650,
        title_x=0.5,
        margin=dict(l=20, r=20, t=70, b=20)
    )

    task2_fig.show()

else:
    print("This graph is available only between 6 PM and 8 PM IST.")

This graph is available only between 6 PM and 8 PM IST.

In [53]:
## Task 2 Insights

#- Only categories with installs greater than one million were included.
#- Representative countries were assigned to visualize the data geographically.

In [54]:
## Task 2 Assumptions

#- The Google Play Store dataset does not contain Country or Region information.
#- Representative countries were assigned solely for visualization purposes.
#- The geographic mapping does not represent the actual origin of installs.
#- All installs, categories and filtering logic were derived from the original dataset.
#- The map is displayed only between 6 PM IST and 8 PM IST.

In [56]:
import os

os.makedirs("tasks/Task_2", exist_ok=True)

category_installs.to_csv(
    "tasks/Task_2/task2_summary.csv",
    index=False
)

print("Task 2 summary saved successfully!")

Task 2 summary saved successfully!

In [70]:
task2_fig.write_html(
    r"C:\Users\Prathamesh\Desktop\Google_Playstore_Project\tasks\Task_2\task2_chart.html"
)

print("✅ Task 2 chart saved successfully!")

✅ Task 2 chart saved successfully!